# Generated by Django 4.0.4 on 2022-10-04 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin_register',
            fields=[
                ('reg_id', models.AutoField(primary_key=True, serialize=False)),
                ('fullname', models.CharField(default='', max_length=200)),
                ('username', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('password', models.CharField(max_length=50)),
                ('photo', models.FileField(blank=True, null=True, upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelname', models.CharField(default='', max_length=200)),
                ('description', models.CharField(default='', max_length=255)),
                ('gib', models.FileField(blank=True, default='', null=True, upload_to='images/')),
                ('price', models.FloatField(default='')),
                ('types', models.CharField(default='', max_length=255)),
                ('format', models.CharField(default='', max_length=255)),
                ('modeltype', models.CharField(default='', max_length=255)),
                ('image', models.ImageField(blank=True, default='', null=True, upload_to='')),
                ('category', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='dmnzApp.categories')),
            ],
        ),
    ]
