# Generated by Django 4.0.4 on 2022-10-06 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmnzApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Register_freelance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(default='', max_length=255)),
                ('country', models.CharField(default='', max_length=255)),
                ('mobile', models.CharField(default='', max_length=255)),
                ('email', models.CharField(default='', max_length=255)),
                ('profile_pic', models.FileField(blank=True, default='', null=True, upload_to='profile/')),
                ('url', models.CharField(default='', max_length=255)),
                ('project_title', models.CharField(default='', max_length=255)),
                ('position2', models.CharField(default='', max_length=255)),
                ('file', models.FileField(blank=True, default='', null=True, upload_to='images/')),
                ('company', models.CharField(default='', max_length=255)),
                ('position', models.CharField(default='', max_length=255)),
                ('Rate', models.CharField(default='', max_length=255)),
                ('start', models.DateField()),
                ('end', models.DateField()),
                ('startdate', models.DateField()),
                ('enddate', models.DateField()),
                ('college', models.CharField(default='', max_length=255)),
                ('special', models.CharField(default='', max_length=255)),
                ('education', models.CharField(default='', max_length=255)),
                ('proffecional_title', models.CharField(default='', max_length=255)),
                ('service', models.CharField(default='', max_length=255)),
                ('skills', models.CharField(default='', max_length=255)),
                ('over_view', models.CharField(default='', max_length=255)),
            ],
        ),
    ]
