# Generated by Django 4.0.4 on 2022-11-04 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dmnzApp', '0004_designation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service_form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(default='', max_length=100)),
                ('phone_number', models.CharField(default='', max_length=100)),
                ('email', models.CharField(default='', max_length=100)),
                ('Address', models.CharField(default='', max_length=100)),
                ('description', models.CharField(default='', max_length=100)),
                ('status', models.CharField(default='', max_length=100)),
                ('service_freelancer', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='dmnzApp.register_freelance')),
            ],
        ),
    ]
